/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.beothorn;

public class App {
    public static int functionThatCallsFunctions(){
        int foo = 0;

        foo = fastFunction(foo);
        foo = slowFunction(foo);
        return foo;
    }

    private static int slowFunction(int foo) {
        for (int i = 0; i < 100000; i++) {
            foo -= 5000;
            for (int j = 0; j < 20000; j++) {
                foo++;
                for (int k = 0; k < 1000; k++) {
                    foo--;
                }
            }
        }
        return foo;
    }

    private static int fastFunction(int foo) {
        for (int i = 0; i < 100000; i++) {
            foo++;
        }
        return foo;
    }

    public static void main(String[] args) {
        System.out.println("Started");
        System.out.println(functionThatCallsFunctions());
        System.out.println("Ended");
    }
}
