/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.beothorn;

import com.github.junrar.Junrar;
import com.github.junrar.exception.RarException;

import java.io.IOException;
import java.util.ArrayList;

public class App {

    private static ArrayList<Integer> allNumbers = new ArrayList<>();

    private static void printNumber(int number) {
        allNumbers.add(number);
        try {
            Thread.sleep(200);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }

    public static void main(String[] args) throws RarException, IOException {
        // new thread that print all numbers up to 100
        new Thread(() -> {
            for (int i = 0; i < 100; i++) {
                printNumber(i);
            }
        }).start();

	printNumber(200000);

        AnotherClass foo = new AnotherClass("Foo");
        foo.getValue();
        String x = foo.toString();
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }

        Junrar.extract("/tmp/foo.rar", "/tmp");
    }
}
